### ISSUE TITLE
[F-R] Browse section.

### ISSUE THREAD

**Issue by VGFlash** [shosetsuorg/android-app#100]
I tried searching for a novel that is available on fastnovel on their site and then on the app.
I was able to find it on the site but was not able to access it on the app and also on fastnovel if you write the author name it finds all the novel by the author but that does not happen in the browse search now.

**Describe the solution you'd like**
If it would be possible to do something that allows us to search for author as well and give consistent search results.

**Describe alternatives you've considered**
No alternative considered

**Additional context**
NA

**Comment by Doomsdayrs** [comment]
Browse filters have been added, I wonder how the current state is
