### ISSUE TITLE
[Bug] Scroll in reader

### ISSUE THREAD

**Issue by VGFlash** [shosetsuorg/android-app#101]
**Describe the bug**
In the reader part of the app whenever a chapter is opened whenever scrolling a little fast it skips the chapters and moves to the next chapter

**To Reproduce**
1. Open any novel
2. Scroll moderately fast
3.  It will skip many lines below and then proceed to the chap end flash screen 

**Expected behavior**
Even on fast scrolling it does not move to next chapter untill the end of chapter.

**Screenshots**
NA

**Device information:**
 - OS: Android 10 January 2021 security patch
 - App Version: 2.0.0-1142

**Additional context**
This bug is fairly difficult to reproduce when trying to reproduce please try to scroll fast for about 10 chapters at least.

**Comment by VGFlash** [comment]
One more thing is that this issue is a bit inconsistent to reproduce.
So when trying to reproduce please try multiple times with scrolling fast to get upto like 10 chapter to test.

**Comment by ram-evre** [comment]
I have this bug too, using the 1136 version.

**Comment by Doomsdayrs** [comment]
Fixed
