### ISSUE TITLE
App crashes sometimes when reopening reading mode

### ISSUE THREAD

**Issue by marky123808** [shosetsuorg/android-app#105]
Every few chapters, when I reach a new chapter, the new chapter only shows the loading symbol but doesn't load. To get past this, I close and reopen reading mode, which sometimes works, but sometimes the app crashes.

**Comment by Doomsdayrs** [comment]
Version?

**Comment by marky123808** [comment]
1137, I'm not sure if they officially  released it yet.

**Comment by AbdullahM0hamed** [comment]
They did - they then unreleased it for being too error-prone, rip

**Comment by marky123808** [comment]
https://discord.com/channels/598920799851905034/718562167074324480/801574163806158900

hmm, it crashes less than 1136 for me

**Comment by Doomsdayrs** [comment]
This has been solved, Turned out to be a NPE due to how Conductor loads things up
