### ISSUE TITLE
[F-R] Improve accessibility for the visually impaired

### ISSUE THREAD

**Issue by leaitan** [shosetsuorg/android-app#106]
My vision isnt bad but not perfect, so the text size on large is still not good

So as a solution you can have an option to change text size in numers, like google docs or something.

**Comment by Doomsdayrs** [comment]
Sure thing!

**Comment by Doomsdayrs** [comment]
Shosetsu opened up configuration of the views even more, How are things now?

**Comment by Doomsdayrs** [comment]
All good now
