### ISSUE TITLE
[F-R] A "novel chapter search feature" in library to directly jump to the required chapter & ability to directly "mark read above" chapters.

### ISSUE THREAD

**Issue by ram-evre** [shosetsuorg/android-app#107]
**Is your feature request related to a problem? Please describe.**
When there are thousands of chapters in a novel, it's hard to scroll so many times. sometimes the scroll directly jumps to end of chapters and have to repeat it again.
Also to mark read chapters we have to select the 1st chapter and then the required chapter which is hard when there are thousands of chapters. sometimes the app even slows down when Marking read.

**Describe the solution you'd like**
Add a search option(probably accessed from the 3 dots). With search, we can directly jump to the chapter we want to read, or even "mark read" the before chapters.
"Mark read above" feature like in tachiyomi where we don't have to select lower and upper limit of chapters to mark read them.

**Comment by RunicAce** [comment]
Instead of a chapter search, I think it would be easier to implement a 'jump to chapter' feature in the reader menu.
