### ISSUE TITLE
Option for disable Left/Right Swipe

### ISSUE THREAD

**Issue by Philii** [shosetsuorg/android-app#109]
When I reading, app randomly ask next chapter.
I'm always frustrated when app ask frequently.
Later I found out, when i scroll, I drag screen little tilt. 
And app assume it as left or right swipe.

So currently I don't read from shosetsu because there is no option to disable it.

**Comment by Doomsdayrs** [comment]
L/R Swipe is not a feature, it is a bug

**Comment by Doomsdayrs** [comment]
Bug is fixed with 4f7b40f
Post 1136 releases will have it patched
