### ISSUE TITLE
Show what novel chapters are updated when library is updated in notification toggle.

### ISSUE THREAD

**Issue by ram-evre** [shosetsuorg/android-app#112]
**Is your feature request related to a problem? Please describe.**
When the novels are updated in the library, it just shows "update complete" in the notification toggle which is very vague on what it does.

**Describe the solution you'd like**
Instead, let it show what novel chapters are updated and how many are updated like in tachiyomi.

**Describe alternatives you've considered**
also maybe show a small red dot on the update tab to show the chapters are updated.

**Comment by Doomsdayrs** [comment]
The update notifications have been updated, now stating a quantity of how many chapters have been updated for which novel

How is it now?

**Comment by Doomsdayrs** [comment]
Seems to be working now
