### ISSUE TITLE
[Bug] Let the reader remember where we left off the last read chapter.

### ISSUE THREAD

**Issue by ram-evre** [shosetsuorg/android-app#114]
**Is your feature request related to a problem? Please describe.**
the chapters go back to the top when we leave them halfway for a while even when we don't clear the app from recent.

**Describe the solution you'd like**
let the app remember the chapter position where we left off. If it consumes too much memory and hard to do, then at least let it remember the last read novel's chapter position instead of all novels. 

**Describe alternatives you've considered**
since the novel is not similar to comics and has one long page, maybe let the reader divide to the top, middle, bottom(or more) segments of the chapter and jump to those segments when depending on where we left off. If we were to left off near the top then let it go to the top if near to the middle then to the middle segments. 
this alternative is written assuming it's hard to make the reader remember the exact position.

**Comment by Doomsdayrs** [comment]
This feature actually has been implemented, the issue is there is a bug messing up positioning
