### ISSUE TITLE
[F-R] Bigger scoll bar in chapter browsing

### ISSUE THREAD

**Issue by Philii** [shosetsuorg/android-app#120]
When Novel which have over 1,000 chapters, Scollbar become very tiny and almost unable to drag it.

' < Novel with chapters 1800
| < Novel with chapters 600

Please set minimum hight for scollbar.
Thank you for your efforts.

**Comment by Philii** [comment]
I will send ss in discord channel.

**Comment by Doomsdayrs** [comment]
Related: https://issuetracker.google.com/issues/64729576

**Comment by Philii** [comment]
Jump Chapter relief this issue.

**Comment by Doomsdayrs** [comment]
Closing because Jump To Chapter solves this issue
