### ISSUE TITLE
[F-R] Font options

### ISSUE THREAD

**Issue by rtrachoo** [shosetsuorg/android-app#121]
I believe adding a feature to change font options would be great for this app. The standard font is okay but it can make the reading experience better if a few good looking fonts were added as an option.

**Comment by Doomsdayrs** [comment]
Need to know a way to get fonts

**Comment by RunicAce** [comment]
For those with Dyslexia, you can add Open dyslexic. It's a free to use font. As for custom font usage, I believe that would be harder than adding fonts in that people can choose from.

**Comment by RunicAce** [comment]
For those with Dyslexia, you can add Open dyslexic. It's a free to use font. As for custom font usage, I believe that would be harder than adding fonts in that people can choose from.

**Comment by LagradOst** [comment]
> 
> 
> Note, Need to know a way to get fonts.

An eazy way to get all system font is via system/fonts
this is the method I used in my project

`fun getAllFonts(): Array<File>? {
            val path = "/system/fonts"
            val file = File(path)
            return file.listFiles()
        }`

**Comment by Doomsdayrs** [comment]
As of the latest versions of Shosetsu, users can use custom CSS to modify how the text looks.
