### ISSUE TITLE
[F-R] Extension Update Notification

### ISSUE THREAD

**Issue by RunicAce** [shosetsuorg/android-app#126]
**Is your feature request related to a problem? Please describe.**
Not that I am aware of

**Describe the solution you'd like**
Well, I have an idea of how it can be done. When pressing the 'reload extensions' button in shosetsu, it'll download a latest_version.txt, compare to a local_version.txt, if there are differences in the file, it'll let you know there are updates available. Since updates require you to uninstall an extension, knowing that one of your extensions has an update would be nice. Each extension can be assigned an ID in the app, where the local_version.txt would have something like "[novel trench ID here] = 1.0.2;"

**Describe alternatives you've considered**
I don't really know how else this could be implemented.

**Additional context**
None

**Comment by Doomsdayrs** [comment]
Shosetsu already does this. Except the identifier is defined by the extension itself from the repository. 

This is a feature that allows overloading of extensions

**Comment by Doomsdayrs** [comment]
Eh I'll keep it open cause I already was patching this up

**Comment by Doomsdayrs** [comment]
This has been added, Just need to enable the notification to be tapped to update
