### ISSUE TITLE
[Bug] [1435 - 1441] Update screen not shown new update

### ISSUE THREAD

**Issue by Philii** [shosetsuorg/android-app#128]
**Describe the bug**
Update screen not shown new update

**To Reproduce**
1. Bookmark novel from 1136
2. Update app to 1441
3  Update novel
4. Nothing in update screen but new chapter in novel

**Device information:**
 - OS: Android 10
 - App Version: 1435 - 1441

**Comment by Doomsdayrs** [comment]
Fixed
