### ISSUE TITLE
[downloading updated chapter not working] [1441

### ISSUE THREAD

**Issue by x3tj16** [shosetsuorg/android-app#129]
**Describe the bug**
After enabling download update chapters , it was supposed to auto download latest updated chapters but it is not working.

**To Reproduce**
1. Enable 'download update chapter'
2. Go to library and update 
3.  Updated chapters are not being downloaded

**Expected behavior**
Updated chapters are to be downloaded automatically

**Screenshots**

**Device information:**
 - OS: Android 9
 - App Version:1441

**Additional context**

**Comment by Philii** [comment]
![Screenshot_2021-07-15-14-45-40-964_com github doomsdayrs apps shosetsu debug](https://user-images.githubusercontent.com/5039175/125753888-24ca0c87-36da-4fa3-90d7-b464b0793ecd.jpg)
Not working for me too. (also update screen not shown)

**Comment by x3tj16** [comment]
I am using 1136 till the bugs are fixed

**Comment by Philii** [comment]
![Screenshot_2021-07-17-20-17-47-401_com github doomsdayrs apps shosetsu debug](https://user-images.githubusercontent.com/5039175/126039139-da2e02c4-3edd-4431-825e-6aa1914a1cc1.jpg)
![Screenshot_2021-07-17-20-17-53-384_com github doomsdayrs apps shosetsu debug](https://user-images.githubusercontent.com/5039175/126039141-398ed889-1b67-4aca-8f41-1b7b98b7d12e.jpg)

auto download work if update screen work.
I think this will fix if #128 fixed.
