### ISSUE TITLE
[Bug] [1441] Reader navbar and statusbar wont go away

### ISSUE THREAD

**Issue by LagradOst** [shosetsuorg/android-app#130]
**Describe the bug**
After you click any dialog in the reader the statusbar and navbar wont go away.

**To Reproduce**
1. In reader click a dialog
2. Close the dialog

**Expected behavior**
The statusbar goes away

**Screenshots**
https://cdn.discordapp.com/attachments/718562167074324480/865046223508996096/Screenshot_20210715_034321_com.github.doomsdayrs.apps.shosetsu.debug.jpg

**Device information:**
 - OS: android sdk 29 (EMUI 10.0.0.189)
 - App Version: 1441

**Comment by Philii** [comment]
I don't use bottom bar.
Please add as option to hide. instance of tap to hidden or shown.

**Comment by Doomsdayrs** [comment]
How is it now? I added an option to toggle
