### ISSUE TITLE
[Bug] [1441] Cant change to light theme

### ISSUE THREAD

**Issue by LagradOst** [shosetsuorg/android-app#131]
**Describe the bug**
Settings > advanced > Theme 
cant change theme at all

**To Reproduce**
1. Just change to light from dark

**Expected behavior**
That it works

**Video**
https://cdn.discordapp.com/attachments/718562167074324480/865055059875463189/SVID_20210715_041924_1.mp4

**Device information:**
 - OS: android sdk 29 (EMUI 10.0.0.189)
 - App Version: 1441

**Comment by Doomsdayrs** [comment]
Fixed
