### ISSUE TITLE
[Bug] [1441] Changing view in Browse section doesn't work

### ISSUE THREAD

**Issue by eemelis** [shosetsuorg/android-app#132]
**Describe the bug**
When in "Browse" tab, the view/card type is decided by the view/card type in "My Library" and cannot be changed from the "Browse section". To Change the view you need to change the view from "My Library". Also compressed view doesn't work properly on "Browse" tab.

**To Reproduce**
1. Change view in "My Library"
2. Go to Browse and go to extension.
3.  Click the views icon at the top and try to change the view. It wont change.
4.  Go to "My library" and change the view there.
5. Go back to "Browse" and select an extension. The view has now changed.

**Expected behavior**
The view button is supposed to change the view. It is also not supposed to be affected by "My library" view setting.

Also the compressed card type is put in a grid rather than a list in "Browse" tab.

**Screenshots**
Screen capture: https://discord.com/channels/598920799851905034/598920799851905036/864944894937137163

**Device information:**
 - OS: Oxygen OS 11.2.7.7.LE15BA
 - App Version: 2.0.0-1441

**Additional context**
-

**Comment by Doomsdayrs** [comment]
Fixed
