### ISSUE TITLE
[F-R]Top margin padding

### ISSUE THREAD

**Issue by RunicAce** [shosetsuorg/android-app#133]
**Is your feature request related to a problem? Please describe.**
Frankly, I would consider this a problem. When using the reader, there is no space between the top text, and the edge of the screen. It also is frequently covered by the top 'chapter number' bar which is rather annoying to have to somehow hide each and every chapter.

**Describe the solution you'd like**
There are a few solutions, but the one I'd like is a combination. Adding some padding to the top margin, and being able to disable the top chapter indicator. After so long, it bugs out anyway.

**Describe alternatives you've considered**
- Increasing the padding so that it is below the chapter indicator
- putting the chapter indicator in line with the text, so the text stays below it
-make it easier to hide the top bar

**Additional context**
![Screenshot_20210717-093417.jpg](https://user-images.githubusercontent.com/38808048/126038737-814ce838-deaa-4839-b87d-d02c052acd86.jpg)
![Screenshot_20210717-093407.jpg](https://user-images.githubusercontent.com/38808048/126038750-3b7785e2-0ab0-49fb-ba20-ac30eeeb8bce.jpg)

**Comment by Doomsdayrs** [comment]
Added some padding in 4d92a360a21ef1ce6931a0987aafb5c1f02d329e

**Comment by Doomsdayrs** [comment]
How is it now?

**Comment by RunicAce** [comment]
Honestly looks like it hasn't changed

![Screenshot_20210722-235756.jpg](https://user-images.githubusercontent.com/38808048/126735831-f4dc68ee-fc04-4af2-86ea-a959fcfe6d4c.jpg)

**Comment by Azuka** [comment]
If possible, can we also add padding to the bottom? At least on a tablet, the text is always too close to the bottom.

**Comment by RunicAce** [comment]
> Honestly looks like it hasn't changed
> 
> ![Screenshot_20210722-235756.jpg](https://user-images.githubusercontent.com/38808048/126735831-f4dc68ee-fc04-4af2-86ea-a959fcfe6d4c.jpg)

Nevermind, after a few days, the padding has updated, it is now visible below the top bar

**Comment by Doomsdayrs** [comment]
With CSS you can ignore this issue. Other then that it seems to have been solved.
