### ISSUE TITLE
[Bug] [2.0.0] What are the values in acra.properties supposed to be? [DEVELOPMENT]

### ISSUE THREAD

**Issue by shipsywor** [shosetsuorg/android-app#137]
**Describe the bug**
Cannot find file `acra.properties` and there is no documentation regarding what the values `acraUsername` and `acraPassword` supposed to be.

**To Reproduce**
1. Clone repo and open in Android Studio.
2. Android Studio displays error when trying to build the project suggesting there is no `acra.properties` file.

**Expected behavior**
Add documentation or comments in code for example here: https://github.com/shosetsuorg/android-app/blob/562816f5d31484683d2a02fde549423097f70d40/android/build.gradle.kts#L54-L55 on what the values are supposed to be.

**Screenshots**

**Device information:**
 - OS: N/A
 - App Version: 2.0.0

**Additional context**
Add helpful README to get started with development. Add steps to setup development.

**Comment by Doomsdayrs** [comment]
You can set them as a dummy value. ACRA reports to the crash server with those keys
