### ISSUE TITLE
[Feature Request] Update from within the app

### ISSUE THREAD

**Issue by hXtreme** [shosetsuorg/android-app#14]
As you had mentioned on Reddit.

I'm just opening a ticket to be able to keep track of it.

**Comment by Doomsdayrs** [comment]
There is an updater, Need to add a downloading option to it

**Comment by Doomsdayrs** [comment]
Progress has been made, Having issues with installer dialog

**Comment by Doomsdayrs** [comment]
This has been working for a while now. :D
