### ISSUE TITLE
[F-R] 

### ISSUE THREAD

**Issue by nasooory** [shosetsuorg/android-app#140]
i want to request 4 websites:-
https://www.69shu.org/
http://m.quanben.me/
https://kolnovel.com/
https://riwyat.com/

and if you can when i save a novel can you make it txt files not html

**Comment by TechnoJo4** [comment]
> i want to request 4 websites

Your are on the wrong repository. All extension requests issues should be opened on <https://github.com/shosetsuorg/extensions>.

Please, check if there is an existing issue and then open one issue for every website. We do not process requests which do not follow our formatting.

> can you make it txt files not html

No. Downloads are meant to be internal to Shosetsu. External usage is not condoned or supported.
