### ISSUE TITLE
[F-R] Mark previous as read

### ISSUE THREAD

**Issue by Azuka** [shosetsuorg/android-app#141]
**Is your feature request related to a problem? Please describe.**
I have a few novels I'm following with chapters in the 100s or 1000s where I'm at the midpoint. It's practically impossible to start where I left off because the process of marking chapters requires me to either select everything then uncheck the ones I haven't read, or manually select hundreds of chapters. Eg I'm at Chapter 1900 in Martial Peak which has 2200+ chapters currently.

**Describe the solution you'd like**
Ideally this works where I can select a chapter and one of the popup menu items is too mark previous chapters as read, or to select two chapters and mark everything in between as either read or unread.

**Describe alternatives you've considered**
As above.

**Additional context**
I think this was part of a separate feature request at #107

**Comment by RunicAce** [comment]
We already have a feature you can use. For example, if you need to mark 5 and 874, then scroll to five, select it, go up to jump, click it, type in 874, and click confirm. This will bring you straight to 874, most likely with it at the bottom of the screen. Then select it,  now click the button shown in the second screenshot.


![Screenshot_20210813-082551.jpg](https://user-images.githubusercontent.com/38808048/129356815-f260e4a7-9088-4dbe-8b86-7b61ce966d67.jpg)
![Screenshot_20210813-082918.jpg](https://user-images.githubusercontent.com/38808048/129357328-5855dd50-f0de-4782-8e22-8bd362acaee2.jpg)

**Comment by Azuka** [comment]
Thanks @RunicAce, that works!
