### ISSUE TITLE
[Bug] [2.0.0-1602] External backups can't be restored

### ISSUE THREAD

**Issue by Kr4u7** [shosetsuorg/android-app#147]
**Describe the bug**
If you create a backup within the app and export it, you cannot restore from that file.
Internal backups (which haven't been exported) seem to work fine

**To Reproduce**
1. Create a backup
2. Export said backup to i.e. Download folder
3. Restore now -> External -> select newly created backup
4. See error namely 'Invalid File'

**Expected behavior**
Restore the backup completely.

**Device information:**
 - OS: Android 11 (LineageOS 18.1)
 - App Version: 2.0.0-1602

**Comment by Doomsdayrs** [comment]
Has this been solved?

**Comment by Doomsdayrs** [comment]
No information provided, Closed.
