### ISSUE TITLE
[F-R] Option to cancel downloads

### ISSUE THREAD

**Issue by Kr4u7** [shosetsuorg/android-app#148]
**Is your feature request related to a problem? Please describe.**
So if I am downloading a few novels with thousands of chapters and some chapters run into a download error (i.e. host not reachable for a time), the download queue is slightly overwhelming.

**Describe the solution you'd like**
Please give us the possibility to cancel pending downloads, so that those chapters don't fill up the queue.
Thanks!

**Comment by Doomsdayrs** [comment]
I am a bit confused, Chapters with a download status of "Pending" have a long press option to delete.

**Comment by Dunbock** [comment]
Yes. After selecting one you get multiple select options. One is select all, one is invert all selected and the last one is to add all chapters in between selected chapters.

**Comment by Doomsdayrs** [comment]
Noted, I shall add an option to delete all

**Comment by Doomsdayrs** [comment]
Closed with 7c9eef0
