### ISSUE TITLE
[F-R] Snackbar Resizing Depending on Downloaded Chapters

### ISSUE THREAD

**Issue by Dunbock** [shosetsuorg/android-app#151]
**Is your feature request related to a problem? Please describe.**
The snackbar resizes itself depending on whether there is a chapter selected, which is downloaded or not. This is frustrating when using the _select all_ options for chapters and then immediately selecting delete. After the _select all_ option a lag spike happens, which then changes the snackbar but the input on the screen does not hit the delete button but the download button.
<img src="https://user-images.githubusercontent.com/8299260/140777141-8248908b-4f34-4c4d-ae0d-32fc9fc3e713.png" alt="drawing" width="200"/> <img src="https://user-images.githubusercontent.com/8299260/140777147-36b9922c-92e2-45f9-b674-1af465a9ff32.png" alt="drawing" width="200"/>

**Describe the solution you'd like**
The snackbar always shows the download and delete option. Optionally it grays them out until they are usable.

**Comment by Doomsdayrs** [comment]
I see the issue in this, I shall edit the code to simply inactivate options instead
