### ISSUE TITLE
[Bug] [1656] Chapter Release (Date) Cut Off

### ISSUE THREAD

**Issue by Dunbock** [shosetsuorg/android-app#153]
**Describe the bug**
The release (date) of a chapter gets cut off if it is to long. Though weirdly cut off, seemingly after a white space.

**To Reproduce**
1. Select a novel on BoxNovel with the default listing.
2. See the release (dates) of chapters.

**Expected behavior**
The complete release date gets displayed.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8299260/140801126-7183a849-bfa1-45d6-90ff-b266644b87dd.png" alt="drawing" width="200"/>

**Device information:**
 - OS: Android 11
 - App Version: 1656

**Comment by khonkhortisan** [comment]
Variation: the second line of date text is partly visible
<img src="https://user-images.githubusercontent.com/1996449/141672049-e841da1c-3073-4b65-b704-2b68daae8ab5.jpg" width="200">

**Comment by khonkhortisan** [comment]
so the solution to wrapped content is to `wrap_content`

**Comment by Doomsdayrs** [comment]
Yes @khonkhortisan , I had limited it because I wanted to persevere consistency in how each chapter looks to the other. Clearly impractical.
