### ISSUE TITLE
[Bug] [2.0.0-1656] Extension settings don't load the first time

### ISSUE THREAD

**Issue by khonkhortisan** [shosetsuorg/android-app#157]
**Describe the bug**
1. The next extension to have its settings opened won't show its settings:
      a. after shosetsu is fully closed 
      b. sometimes after opening it from the list of running apps), the next extension to have its settings opened won't show its settings.
   and it'll
      c. sometimes say This extension has no settings!
      d. sometimes not say that

**To Reproduce**
1. Open shosetsu
2. Switch to Browse tab
3. Click any settings gear ⚙️
4. See the extension image, name, id, filename, language, trashbutton
5. Don't see the listings dropdown nor any other settings
6. Click back ←
7. Click any settings gear ⚙️, not necessarily the same one as before
8. Step 4 "See the extension image, name, id, filename, language, trashbutton"
9. Opposite of step 5, see the listings dropdown and any other settings

**Expected behavior**
Click any settings gear ⚙️, see the listings dropdown and any other settings

**Screenshots**
<img src="https://user-images.githubusercontent.com/1996449/141679565-544f7b55-b39c-4585-bd90-a03e68deeb43.jpg" width="25%"><img src="https://user-images.githubusercontent.com/1996449/141679574-ffbf458e-d8b8-4334-9d3f-16e2ed74867f.jpg" width="25%"><img src="https://user-images.githubusercontent.com/1996449/141679565-544f7b55-b39c-4585-bd90-a03e68deeb43.jpg" width="25%"><img src="https://user-images.githubusercontent.com/1996449/141679562-e196112f-3094-466d-8796-47574c7b62cd.jpg" width="25%">
<img src="https://user-images.githubusercontent.com/1996449/141680139-07cb7003-6852-4316-8e82-eceab02e7e5b.jpg" width="25%">

**Device information:**
 - OS: Android 10, One UI 2.0
 - App Version: 2.0.0-1656
 - Phone: Samsung Galaxy A20 SM-A205U
 - Display: 2340×1080 virtual resolution downscaled onto a 1560×720 physical display (1.5² pixels in every 1² pixel)

AND
- BlueStacks 5.3.145.1003 N64, 1 core, 900MB memory, low memory performance mode, 30fps, portrait 540×960, 240 dpi, phone: OnePlus 5, ATNT

**Additional context**

**Comment by Doomsdayrs** [comment]
This is my priority right now, I am working on replacing the old hacked together extension settings with jetpack compose and proper techniques

**Comment by Doomsdayrs** [comment]
Fixed with b770d4d
