### ISSUE TITLE
[Bug] [1656] Drop Down List Dark Theme Text Colour

### ISSUE THREAD

**Issue by Dunbock** [shosetsuorg/android-app#159]
**Describe the bug**
The text colour of any drop down list is black in dark theme instead of white like all the other text.

**To Reproduce**
1. Enable dark theme (Settings > Advanced).
2. See drop down text being black on gray background, instead of white or red compared to the other text.

**Expected behavior**
The text colour of the drop down lists is white to enable far easier reading.

**Screenshots**
<img src="https://user-images.githubusercontent.com/8299260/141686562-edcf12bd-0fff-4e8e-a182-3ce67973ca46.png" alt="drawing" width="200"/>

**Device information:**
 - OS: Android 11
 - App Version: 1656

**Comment by Doomsdayrs** [comment]
Attempted to solve in a4f939b , Theming is a pain in android

**Comment by khonkhortisan** [comment]
Oops, this wasn't fixed for:
Settings > Reader → Text Alignment
Settings > Reader → Paragraph indent
Settings > Reader → Marking method
Reader → Paragraph indent

drawer_layout - DrawerLayout
	coordinator - CoordinatorLayout
		controller_container - ChangeHandlerFrameLayout
			recyclerView - RecyclerView
				itemView - ConstraintLayout
					rightField - ConstraintLayout
						spinner - AppCompatSpinner
							#000000 outlineAmbientShadowColor
							#000000 outlineSpotShadowColor
							#000000 solidColor
CoordinatorLayout
	chapter_reader_bottom_scroll - NestedScrollView
		recyclerView - RecyclerView
			itemView - ContraintLayout
				rightField - ConstraintLayout
					spinner - AppCompatSpinner
						#000000 outlineAmbientShadowColor
						#000000 outlineSpotShadowColor
						#000000 solidColor
