### ISSUE TITLE
[F-R] Change to the "Jump" button

### ISSUE THREAD

**Issue by DeeJack** [shosetsuorg/android-app#171]
The problem with the feature "Jump", which allows getting directly to one chapter from the list of chapters, is that because of the animation it takes some time to get to that chapter. With short novels it's not a problem, but recently I'm reading "The legendary mechanic" and to get to chapter 1000 it takes 13 seconds (I checked) every time I have to get there. If we take even longer novels like "Super Genes" with 3000 chapters it's even longer.

**Describe the solution you'd like**
To either remove the animation and directly get to the chapter, or to shorten the duration of the animation.

**Comment by Doomsdayrs** [comment]
13 seconds is plenty of time for you to take your eyes off the screen, drink some water, get some snacks, walk around

I see no downsides (sarcasm)

I shall work on a solution
