### ISSUE TITLE
[Suggestion] Changes in Settings

### ISSUE THREAD

**Issue by hXtreme** [shosetsuorg/android-app#23]
Rename Credits to Info and in Info display the following:

Disclaimer

App version

Author

Bug report link

License

**Comment by hXtreme** [comment]
Can you assign this issue to me?

**Comment by Doomsdayrs** [comment]
Sure thing

**Comment by Doomsdayrs** [comment]
what would be a Disclaimer?

**Comment by hXtreme** [comment]
A disclaimer should contain the legal spiel saying that this app is not affiliated with the websites and the sort (often you can find template disclaimers for whatever license you're using and then you can edit on top of that)

**Comment by Doomsdayrs** [comment]
Its been a long time
