### ISSUE TITLE
[Suggestion] Batch downloading

### ISSUE THREAD

**Issue by BanditKingJing** [shosetsuorg/android-app#30]
currently the only way to download for offline reading is to click one at a time or use the inefficient "select between" to download a bunch at once. Since you're using takiyomi as a reference for design and flow they have it setup at "Download next 10" which is a quick and easy way to download a bunch or a sample of a novel.

so far great work!
![ZomboDroid_02082019234948](https://user-images.githubusercontent.com/53633953/62407167-f528a100-b581-11e9-9268-4f6476a00d15.jpg)
Takiyomi process pic. Menu, Download, Options!

**Comment by Doomsdayrs** [comment]
Semi implemented, Just a logic pain so i didn't do all of it

**Comment by Doomsdayrs** [comment]
Nearly completed this feature, Need to add the more fringe options and it will be complete
