### ISSUE TITLE
[BUG] Back button behaviour

### ISSUE THREAD

**Issue by hXtreme** [shosetsuorg/android-app#39]
Please see the [video](https://youtu.be/O14oC6eUPtM)

Ideal behaviour on pressing back button on the following screen: (incomplete list)

| Screen  | Behaviour  |
|---|---|
| Library  | Exit App  |
| Settings, Download...  | Goto Library  |
| Sub-settings  | Goto Settings  |

**Comment by Doomsdayrs** [comment]
Done
