### ISSUE TITLE
[Bug] crashes when minimized for some time 

### ISSUE THREAD

**Issue by BanditKingJing** [shosetsuorg/android-app#41]
Less of a bother now that the continue button is there but still happens.

I juse close and "Continue"

![Screenshot_20190809-085657_Shosetsu](https://user-images.githubusercontent.com/53633953/62780510-de9faf80-ba83-11e9-8c6f-dcab11763755.jpg)

**Comment by Doomsdayrs** [comment]
Can you elaborate on this issue?

**Comment by Doomsdayrs** [comment]
Is this still occurring? I need crash logs to properly fix it if so

**Comment by Doomsdayrs** [comment]
This now only occurs when in reader for an extended period of time

**Comment by Doomsdayrs** [comment]
Solved
