### ISSUE TITLE
[ENHANCEMENT]  Overhaul of UI schema

### ISSUE THREAD

**Issue by Doomsdayrs** [shosetsuorg/android-app#48]
# Main theme

1. Custom colors
2. Adjustable sizes

# Overhaul reader
1. Change text color separately
2. Change background color separately
3. Have 3 'default' colors. Light, Night, Sepia

**Comment by hXtreme** [comment]
You may want to give Revolution IRC app's theming options a glance.

**Comment by Doomsdayrs** [comment]
0d9d001 adds sepia mode

**Comment by Doomsdayrs** [comment]
There has been enough overhaul, closing
