### ISSUE TITLE
[Bug] Bullet points don't show text

### ISSUE THREAD

**Issue by BanditKingJing** [shosetsuorg/android-app#49]
Something has been feeling off due to random blank spaces.

Turns out when a LN has a table the cells don't translate well. 

Here it's used for item descriptions. 

![Screenshot_20190926-223900_Shosetsu](https://user-images.githubusercontent.com/53633953/65738207-15bb3600-e0af-11e9-9b9c-3594c4734b16.jpg)
![Screenshot_20190926-224158_Shosetsu](https://user-images.githubusercontent.com/53633953/65738211-18b62680-e0af-11e9-9045-b1cc3a43595c.jpg)
http://novelfull.com/the-legendary-moonlight-sculptor/volume-8-chapter-2.html

**Comment by BanditKingJing** [comment]
Narrowed down the issue to bullet points.

**Comment by BanditKingJing** [comment]
This bug is a deal breaker for me since lots of info is given via tables and bullet points. I've stopped using the app now for 2 weeks. Waiting until this bug is finished or I read a new story that doesn't use bullet points.

**Comment by Doomsdayrs** [comment]
I'm sorry for the unfortunate issue, Currently when MD is implemented this should be possible

**Comment by BanditKingJing** [comment]
![ZomboDroid 21122019152745](https://user-images.githubusercontent.com/53633953/71313403-7f28b780-2406-11ea-92b8-1df770b53d33.jpg)

Issue persists with bullet points in New dev build

**Comment by Doomsdayrs** [comment]
I believe that the user notified me on discord that the issue was the source. Closing
