### ISSUE TITLE
[Bug] Slow loadup times, Compared to tachiyomi instant timings

### ISSUE THREAD

**Issue by Doomsdayrs** [shosetsuorg/android-app#58]
**Describe the bug**
App takes 20 seconds to boot, Tachiyomi is instant

**To Reproduce**
- Boot app

**Expected behavior**
Quick fluid bootup

**Screenshots**
https://cdn.discordapp.com/attachments/598974389731459073/662076921873563650/MrwClenOx7.gif

**Device information:**
 - OS: LDPlayer 3.76
 - App Version: v1.0.0

**Comment by Doomsdayrs** [comment]
(Issue from 304648989935140876)

**Comment by hXtreme** [comment]
One thing that can be done once you move the startup code to Kotlin is to lazy load resources.

**Comment by Doomsdayrs** [comment]
Solved
