### ISSUE TITLE
[Bug] chapter order incorrect

### ISSUE THREAD

**Issue by BanditKingJing** [shosetsuorg/android-app#68]
**Describe the bug**
Chapter order isn't sequential. 
See photos. 

**To Reproduce**
1. Open any novel
2. Scroll around to see

**Expected behavior**
Chapters should be ascending or descending 1~2000 in order. 

**Screenshots**
![Screenshot_20200203-221954_Shosetsu](https://user-images.githubusercontent.com/53633953/73711139-eeffb280-46d3-11ea-95e6-34a5404ef45c.jpg)
![Screenshot_20200203-222033_Shosetsu](https://user-images.githubusercontent.com/53633953/73711148-f3c46680-46d3-11ea-9379-fb2edad68782.jpg)

**Device information:**
 - OS: android 8.0
 - App Version: 1.1.3r618

**Comment by Doomsdayrs** [comment]
Obsoleted with sort options
