### ISSUE TITLE
[ENHANCEMENT] I belive that you should add a feature simmular to on of techiyomi's

### ISSUE THREAD

**Issue by tea-man-lol** [shosetsuorg/android-app#75]
I think adding the feature of using volume buttons to scroll as an optian in the reader. The reasen I belive this would be a good enhancement is becouse: I don't know about others but personally I find that scrolling normally for a prolonged time hurts my thumb whereas pushing the volume butten is a less strenuas task.
Sorry if there are any misspellings as I am on my phone and have the dreaded fat thumb syndrome.

**Comment by Doomsdayrs** [comment]
Has been added
