### ISSUE TITLE
[Bug] Rotating screen resets chapter display order

### ISSUE THREAD

**Issue by Zehra** [shosetsuorg/android-app#77]
**Describe the bug**
Display order of chapters is reset when rotating screen, if chapter order is changed.

**To Reproduce**
1. Select a given novel and open index of said novel.
2. Change order of chapters. (If latest, set to oldest, if oldest, set to newest.)
3.  Rotate or change orientation of screen.
4. Error occurs: Order of chapters is reset back to previous setting.

**Expected behavior**
Chapter order should not change upon changing screen orientation or rotation.

**Device information:**
 - OS: **Android 5.1**
 - App Version: v1.1.3-release

**Additional context**
Tested with two different extensions. It appears to be a bug within the main app.

**Comment by Doomsdayrs** [comment]
Cannot to be applied to latest commits anymore
