### ISSUE TITLE
[Bug] [Cosmetic] Download screen formatting

### ISSUE THREAD

**Issue by BanditKingJing** [shosetsuorg/android-app#79]
**Describe the bug**
Downloads page need formatting adjustment. Title need word wrap. 

**To Reproduce**
1. Open the downloads page. In portrait. 
2. See the error.
3.  Flip landscape and it looks better. 
4. Flip back
5. See error again

**Expected behavior**
Expect to see the title in two lines so I can read it. 

**Screenshots**
![Screenshot_20200913-092015_Shosetsu](https://user-images.githubusercontent.com/53633953/93019118-fd377a80-f5a2-11ea-8c8a-e50422502b0e.jpg)
![Screenshot_20200913-091934_Shosetsu](https://user-images.githubusercontent.com/53633953/93019119-fdd01100-f5a2-11ea-9296-6227030681d2.jpg)
![Screenshot_20200913-091921_Shosetsu](https://user-images.githubusercontent.com/53633953/93019120-fdd01100-f5a2-11ea-8733-dde1d2ec191f.jpg)

**Device information:**
 - OS: android 9
 - App Version: r932

**Additional context**

**Comment by Doomsdayrs** [comment]
Solved
