### ISSUE TITLE
[F-R] {Add scrolling using volume buttons}

### ISSUE THREAD

**Issue by lolzkatXD** [shosetsuorg/android-app#81]
**Describe the feature briefly**
I want to be able to scroll while reading without touching the screen. 

**Possible ways to implement**
👆👉👆👈👇👉👆👆👈👉👇👌👉👈👉👇👉👆👈🤏☠️🤙🤙🤙 

**Why is it important**
Makes it so people can binge read easier.

**Comment by lolzkatXD** [comment]
done lol

**Comment by Doomsdayrs** [comment]
In dev*
