### ISSUE TITLE
[Bug] Downloads all stuck as pending

### ISSUE THREAD

**Issue by mcdarklight** [shosetsuorg/android-app#85]
Download status all in pending
Tried to use download all features but it only stuck as pending status

1. Go to library
2. Choose 1 novel
3.  Use the "download all"

**Expected behavior**
1. How to download the chapter?
2. If not possible, how to clear the pending status in download instead

**Comment by Doomsdayrs** [comment]
Solved with new features to delete / set pending / pause buttons added to downloads list
