### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by melnation-com** [shosetsuorg/android-app#86]
**Describe the bug**
Unfortunately, Shosetsu has stopped error shows when I try to run it.

**To Reproduce**
1. Own an Android 5.1.1 device or emulator
2. Install shosetsu-v1.2.0-r1027.apk or shosetsu-v1.2.0-r1026.apk
3.  Installs successfully
4. "Unfortunately, Shosetsu has stopped." error shows

**Expected behavior**
The app will run like the non-v2 I tried.

**Screenshots**
https://snipboard.io/3eAxYm.jpg

**Device information:**
 - OS: Android 5.1.1
 - App Version: shosetsu-v1.2.0-r1027.apk and shosetsu-v1.2.0-r1026.apk are the ones I've tried.

**Additional context**
I tried the non v2 and it works, but you said you will depreciate it so I tried v2 but it does not work.

Can it be fixed by just lowering the android requirement? I don't know what android 5.1.1 doesn't have can it just be provided by a 3rd party app? 

I don't know what's the deal, advanced and technical apps like ibisPaint X, Canva Pro and Screen Translate can even be installed and work flawlessly on this device, What am I missing? for something that just loads a wall of text, it sure requires a bit high of an OS. Just a fair judgement.

**Comment by melnation-com** [comment]
Sorry for the title and being impolite, I can't edit this shiz anymore.

Title should had been "Unfortunately, Shosetsu has stopped"

**Comment by sebbu2** [comment]
Perhaps it is similar to the issue I have with shosetsu 1.2 since r989 (last working version), as i'm also using android 5.1.1

**Comment by melnation-com** [comment]
Yeah I can confirm r989 is the last working version, I searched in the discord with 'r989' and u can see people saying r989 and below are the last working versions. 

And sorry dev for being rude, as I said I can't edit it anymore T.T

**Comment by Doomsdayrs** [comment]
Solved with latest 1058+ commits
