### ISSUE TITLE
Banned from discord

### ISSUE THREAD

**Issue by jpdc** [shosetsuorg/android-app#88]
Hey, ever since the whole apology, I haven't been able to join the shosetsu discord. I want to download the new releases. I don't konow if you banned everyone when you went away for a bit. The Fdroid version keeps giving me the apology message every time I open it.

Can you unban me from discord?

Nitecrawlerjpd#4632

**Comment by Doomsdayrs** [comment]
aren't you an alt of duc?

Also, https://github.com/shosetsuorg/shosetsu-preview exists

**Comment by jpdc** [comment]
Nope, I don't know who that is. It was probably a misunderstanding on your part.

**Comment by Doomsdayrs** [comment]
Unbanned
