### ISSUE TITLE
[F-R] Translate Novels

### ISSUE THREAD

**Issue by RickyM7** [shosetsuorg/android-app#89]
### Describe the feature briefly
This would be an option to translate the novel into your language, such as a translation extension used in browsers.

### Possible ways to implement
Sites such as [Microsoft Translator](https://www.bing.com/translator) or [DeepL](https://www.deepl.com/translator) could be used to translate novels. An icon representing the translator could be right next to the chapter name (in the top bar inside the chapter reader). This translator would automatically detect the selected idoma on the mobile phone or have an option in the settings to select the language to which the novels should be translated.

### Why is it important
This feature is extremely useful in my opinion as it allows any novel in any language to be read by anyone in your language. This would help a lot anyone who wants to read some novel but unfortunately does not have it available in their language anywhere.

**Comment by Doomsdayrs** [comment]
Sadly this is beyond the scope of this application. With the new repository system you can hookup your own translation service.
