### ISSUE TITLE
[Bug] A display issue

### ISSUE THREAD

**Issue by franklinbill** [shosetsuorg/android-app#91]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is v1.1.4-release (27) , my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

<img width="471" alt="bug-shoset" src="https://user-images.githubusercontent.com/18572115/103196361-09133680-491f-11eb-9f16-8d10a3c2e1ee.png">

**To Reproduce**
1. use the largest font and display
2. in the first page
3. See error

**Expected behavior**
I suggest that you can set the width and height of the component to adaptive text

**Screenshots**
<img width="471" alt="bug-shoset" src="https://user-images.githubusercontent.com/18572115/103196430-29db8c00-491f-11eb-976f-7a0de826b874.png">

**Device information:**
 - OS: 8.0
 - App Version:v1.1.4-release (27) 

**Additional context**

**Comment by TechnoJo4** [comment]
Stable (v1) releases are months old.
They are not maintained anymore, and we heavily recommended against their use.
Please use the preview releases, available [here](https://github.com/shosetsuorg/shosetsu-preview/releases).

**Comment by franklinbill** [comment]
Thanks*3000 for your reply! The bug in the new version has been fixed.
