### ISSUE TITLE
[F-R] Managing Novel sources

### ISSUE THREAD

**Issue by TechnoHT** [shosetsuorg/android-app#92]
Describe the feature briefly
> let user choose/add their favorite novel sources from community extensions.

Possible ways to implement
> In my opinion it might similar to what Tachiyomi ( a manga reader app ) did. Use extensions as a source to browse novels title.
Extension might be better if it have filter for genre, year of release,.......

Why is it important
>in the future there might be a lot of users use this app as their novel reader, and they come from different countries, so adding extensions would help them don't have be bound with limited source and not in their favorite language.

**Comment by AriaMoradi** [comment]
Shosetsu already has this feature, if you are possibly talking about custom extension repositories, it is planned.

**Comment by Doomsdayrs** [comment]
Implemented
