### ISSUE TITLE
[F-R] Setting to Auto bookmark novel if chapter is downloaded

### ISSUE THREAD

**Issue by leaitan** [shosetsuorg/android-app#94]
When you download something from a source it downloads the chapters, but sometimes i forget to heart the novel, so i have to go through all my sources to see which source i used to download that novel.

So when you start a download on a novel from a source, it auto saves it to the library so you know which source you got it from

**Comment by Doomsdayrs** [comment]
I love this idea, I'll work to implement it

**Comment by Doomsdayrs** [comment]
It has been implemented~
