### ISSUE TITLE
[Bug] Downloaded and bookmarked filters don't work

### ISSUE THREAD

**Issue by Unicorn-03** [shosetsuorg/android-app#95]
**Describe the bug**
When you select either the downloaded or bookmarked filters inside a novel the app crashes.

**To Reproduce**
1. Open a novel
2. Tap Filter
3. Tap downloaded/bookmarked
4. App crashes

**Expected behavior**
The app filters the chapters according to the selected filter without crashing

**Device information:**
 - OS: Android 10 (MIUI 12.0.3)
 - App Version: 2.0.0-1136

**Comment by Doomsdayrs** [comment]
Fixed
