### ISSUE TITLE
[Bug] Chapters download randomly (?)

### ISSUE THREAD

**Issue by Krilies** [shosetsuorg/android-app#96]
**Describe the bug**

**To Reproduce**
1. First step
2. Second step
3.  '....'

**Expected behavior**

**Screenshots**

**Device information:**
 - OS: 
 - App Version:

**Additional context**

**Comment by Destro9000** [comment]
1142 is a bugged version , downgrade to 1136 and let the dev knows if it still occure

**Comment by Doomsdayrs** [comment]
Does this *still* happen?

**Comment by Doomsdayrs** [comment]
Stale
