### ISSUE TITLE
[Bug]UpdateWorker:0 Toast Notification 

### ISSUE THREAD

**Issue by chaoticchoas** [shosetsuorg/android-app#99]
I seem to be getting this specific toast Notification A couple of times each hour.

This is a screenshot of Toaster App which shows the latest(At the time of taking the screenshot) Toast notification I have received from Shosetsu.
![5cc7cea8c4a16ccf58c795c5145725f061a81514-1](https://user-images.githubusercontent.com/53848074/106418370-c5c74e80-641b-11eb-9a7a-737ba114aa97.jpg)

LG V20 
Alpha Omega Rom 
Android 8.0
Latest Dev Release Shosetsu Preview r1136

I would have posted the log files but I couldn't find them.

**Comment by Doomsdayrs** [comment]
Usually it means a general error occurred. Something that generally happens

But, It should not occur so often, and on the hourly time

**Comment by chaoticchoas** [comment]
> Usually it means a general error occurred. Something that generally happens
> But, It should not occur so often, and on the hourly time
 This might be relevant but I also got a ReportEceptionUsecase: 16, UpdateWorker 2:failed to connect to Bestlightnovel.com. There is more but Ill have to manually search the to find the odd ones out.

**Comment by Doomsdayrs** [comment]
So since this last occured, I changed default update timings and fix the option to change the cycle.

But does this still occur?

**Comment by Doomsdayrs** [comment]
Stale
